In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Replace these with your actual app token
app_token = "iQnHnn5JseouXHtXBQDeMyDch"

# Initialize the client with your app token
client = Socrata("data.cityofnewyork.us", app_token, username="mahmoudelsayed121810@gmail.com", password="M@rkseven11")

# Now you can use the authenticated client to make requests to the API.
# Example: Get the first 2000 results from the dataset "yjf6-ewhz" and convert it to a pandas DataFrame.
results = client.get("yjf6-ewhz", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [4]:
pd.set_option('display.max_columns', None)
results_df.head(20)

,crash_date,crash_time,on_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,off_street_name,cross_street_name,contributing_factor_vehicle_3,contributing_factor_vehicle_4,vehicle_type_code_3,vehicle_type_code_4,contributing_factor_vehicle_5,vehicle_type_code_5
0,2023-10-06T00:00:00.000,10:00,WEST 155 STREET,1,0,0,0,0,0,1,0,Driver Inattention/Distraction,Unspecified,4668398,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-10-06T00:00:00.000,12:22,UTOPIA PARKWAY,1,0,0,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4668413,Sedan,Station Wagon/Sport Utility Vehicle,QUEENS,GRAND CENTRAL PARKWAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-10-06T00:00:00.000,9:02,HERKIMER STREET,0,0,0,0,0,0,0,0,Passing Too Closely,Unspecified,4668428,Sedan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-10-06T00:00:00.000,17:53,EAST 156 STREET,1,0,1,0,0,0,0,0,Unspecified,NaN,4668418,Box Truck,NaN,BRONX,3 AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-10-06T00:00:00.000,16:52,WESTCHESTER AVENUE,1,0,1,0,0,0,0,0,Unspecified,NaN,4668407,Station Wagon/Sport Utility Vehicle,NaN,BRONX,JACKSON AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2023-10-06T00:00:00.000,19:07,NaN,0,0,0,0,0,0,0,0,Alcohol Involvement,Unspecified,4668411,Sedan,Station Wagon/Sport Utility Vehicle,BROOKLYN,NaN,2722 GERRITSEN AVENUE,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-10-06T00:00:00.000,13:00,FORBELL STREET,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4668666,Sedan,NaN,BROOKLYN,MC KINLEY AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2023-10-06T00:00:00.000,22:05,EASTERN PARKWAY,1,0,0,0,1,0,0,0,Driver Inattention/Distraction,Unspecified,4668732,Sedan,Bike,BROOKLYN,BEDFORD AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-10-06T00:00:00.000,10:14,3 AVENUE,1,0,0,0,1,0,0,0,Driver Inattention/Distraction,Alcohol Involvement,4668275,Taxi,Bike,NaN,64 STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-10-06T00:00:00.000,20:50,NaN,0,0,0,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,4668691,Ambulance,NaN,BRONX,NaN,1309 HICKS STREET,NaN,NaN,NaN,NaN,NaN,NaN
10,2023-10-06T00:00:00.000,22:45,60 STREET,1,0,1,0,0,0,0,0,Unspecified,NaN,4668363,Station Wagon/Sport Utility Vehicle,NaN,BROOKLYN,FORT HAMILTON PARKWAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2023-10-06T00:00:00.000,7:49,4 AVENUE,1,0,0,0,1,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4668336,Sedan,Bike,BROOKLYN,5 STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2023-10-06T00:00:00.000,18:35,EAST 178 STREET,0,0,0,0,0,0,0,0,Passing Too Closely,View Obstructed/Limited,4668905,Pick-up Truck,Bike,BRONX,VYSE AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2023-10-06T00:00:00.000,16:45,KENT AVENUE,1,0,0,0,1,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4668838,Bike,Sedan,BROOKLYN,NORTH 7 STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2023-10-06T00:00:00.000,8:57,BERGEN STREET,1,0,0,0,0,0,1,0,Failure to Yield Right-of-Way,Unspecified,4668757,Moped,Moped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2023-10-06T00:00:00.000,16:10,NaN,1,0,0,0,0,0,0,0,Unspecified,Unspecified,4668389,Station Wagon/Sport Utility Vehicle,E-Bike,BROOKLYN,NaN,2569 OCEAN AVENUE,NaN,NaN,NaN,NaN,NaN,NaN
16,2023-10-06T00:00:00.000,2:45,NICHOLS AVENUE,3,0,0,0,0,0,0,0,Traffic Control Disregarded,Unspecified,4668663,E-Scooter,Sedan,BROOKLYN,JAMAICA AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2023-10-06T00:00:00.000,0:00,NANSEN STREET,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4668745,Sedan,NaN,QUEENS,SELFRIDGE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2023-10-06T00:00:00.000,6:16,NaN,1,0,0,0,0,0,1,0,Illnes,NaN,4668471,Station Wagon/Sport Utility Vehicle,NaN,BROOKLYN,NaN,525 LAFAYETTE AVENUE,NaN,NaN,NaN,NaN,NaN,NaN
19,2023-10-06T00:00:00.000,14:15,NaN,1,0,1,0,0,0,0,0,Backing Unsafely,NaN,4668496,Sedan,NaN,MANHATTAN,NaN,9 EAST 40 STREET,NaN,NaN,NaN,NaN,NaN,NaN