In [1]:
from lookups import MAIN_SOURCE_URL, FIRST_CSV_FILE_PATH
from misc_handler import download_and_read_csv
import pandas as pd

url = "https://data.cityofnewyork.us/api/views/yjf6-ewhz/rows.csv?accessType=DOWNLOAD"
local_file_path = r"C:\Users\Admin\Desktop\SEF-Final-Project-NYC-Accidents-Analysis\csv_tables\test.csv"
df = download_and_read_csv(local_file_path, url)

In [2]:
df.shape

NameError: name 'df' is not defined

In [1]:
df

NameError: name 'df' is not defined

In [3]:
df['BOROUGH'].unique()

array([nan, 'BROOKLYN', 'BRONX', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND'],
      dtype=object)

In [4]:
df["BOROUGH"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2032973 entries, 0 to 2032972
Series name: BOROUGH
Non-Null Count    Dtype
--------------    -----
1400526 non-null  object
dtypes: object(1)
memory usage: 15.5+ MB

In [5]:
from cleaning_dfs_handler import clean_nyc_traffic_data

df = clean_nyc_traffic_data(df=df)

In [6]:
df['BOROUGH'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2032973 entries, 1967127 to 1924040
Series name: BOROUGH
Non-Null Count    Dtype
--------------    -----
2004964 non-null  object
dtypes: object(1)
memory usage: 95.5+ MB

In [7]:
from cleaning_dfs_handler import cross_street_mapping
df['BOROUGH'] = df['BOROUGH'].astype(str)
df['CROSS STREET NAME'] = df['CROSS STREET NAME'].astype(str)
def replace_null_borough_with_cross_street(df, street_name_dict):
    for index, row in df.iterrows():
        if pd.isna(row['BOROUGH']) and not pd.isna(row['CROSS STREET NAME']):
            cross_street_name = row['CROSS STREET NAME']
            if cross_street_name in street_name_dict:
                df.at[index, 'BOROUGH'] = street_name_dict[cross_street_name]
    return df

df = replace_null_borough_with_cross_street(df, cross_street_mapping)

In [8]:
df["BOROUGH"].info()

<class 'pandas.core.series.Series'>
Int64Index: 2032973 entries, 1967127 to 1924040
Series name: BOROUGH
Non-Null Count    Dtype
--------------    -----
2032973 non-null  object
dtypes: object(1)
memory usage: 95.5+ MB

In [10]:
pd.set_option('display.max_columns', None)

In [ ]:
df['BOROUGH'].info()

In [11]:
df.head(30)

,CRASH DATE,CRASH TIME,BOROUGH,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1967127,2023-10-09,23:50:00,BROOKLYN,BELT PARKWAY,nan,NaN,0.0,0.0,0,0,0,0,0,0,Alcohol Involvement,Unspecified,NaN,NaN,NaN,4669317,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1967707,2023-10-09,23:10:00,MANHATTAN,NaN,nan,59 WEST 44 STREET,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669164,Station Wagon/Sport Utility Vehicle,Box Truck,NaN,NaN,NaN
1966246,2023-10-09,23:02:00,BROOKLYN,OCEAN PARKWAY,CHURCH AVENUE,NaN,1.0,0.0,0,0,0,0,1,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669243,Sedan,Sedan,NaN,NaN,NaN
1967746,2023-10-09,23:00:00,MANHATTAN,1 AVENUE,EAST 46 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669154,Sedan,Van,NaN,NaN,NaN
1967789,2023-10-09,22:59:00,QUEENS,114 STREET,nan,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4669294,Sedan,Sedan,NaN,NaN,NaN
1967671,2023-10-09,22:55:00,QUEENS,21 STREET,43 AVENUE,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4669228,Motorscooter,NaN,NaN,NaN,NaN
1967784,2023-10-09,22:45:00,QUEENS,NaN,nan,131-22 LAURELTON PARKWAY,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,Unspecified,Unspecified,NaN,4669452,Pick-up Truck,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,NaN
1966309,2023-10-09,21:35:00,BROOKLYN,CHURCH AVENUE,EAST 8 STREET,NaN,1.0,0.0,0,0,1,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669236,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
1966240,2023-10-09,21:25:00,QUEENS,67 DRIVE,110 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Backing Unsafely,Unspecified,NaN,NaN,NaN,4669186,Pick-up Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1967745,2023-10-09,21:16:00,BROOKLYN,BELT PARKWAY,nan,NaN,0.0,1.0,0,1,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4669429,Sedan,NaN,NaN,NaN,NaN
1967780,2023-10-09,21:11:00,BROOKLYN,KINGSLAND AVENUE,EAST GUN HILL ROAD,NaN,3.0,0.0,0,0,0,0,3,0,Other Vehicular,Other Vehicular,NaN,NaN,NaN,4669250,Taxi,Sedan,NaN,NaN,NaN
1966302,2023-10-09,20:47:00,BRONX,EAST BURNSIDE AVENUE,ANTHONY AVENUE,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669203,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
1967773,2023-10-09,20:45:00,BROOKLYN,BROOKLYN QUEENS EXPRESSWAY,nan,NaN,4.0,0.0,0,0,0,0,4,0,Driver Inattention/Distraction,Following Too Closely,Following Too Closely,Following Too Closely,Unspecified,4669132,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,Sedan
1967738,2023-10-09,20:42:00,QUEENS,LIBERTY AVENUE,127 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4669150,Sedan,Dump,NaN,NaN,NaN
1967725,2023-10-09,20:36:00,BROOKLYN,NaN,nan,305 8 AVENUE,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669123,Taxi,Sedan,NaN,NaN,NaN
1967390,2023-10-09,20:30:00,BROOKLYN,BAY RIDGE AVENUE,nan,NaN,1.0,0.0,0,0,1,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669137,Sedan,E-Bike,NaN,NaN,NaN
1966307,2023-10-09,20:20:00,BROOKLYN,AVENUE L,EAST 92 STREET,NaN,3.0,0.0,0,0,0,0,3,0,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,4669156,Sedan,Sedan,NaN,NaN,NaN
1966242,2023-10-09,20:18:00,QUEENS,BELT PARKWAY,nan,NaN,2.0,0.0,0,0,0,0,2,0,Lost Consciousness,Unspecified,NaN,NaN,NaN,4669307,Sedan,Sedan,NaN,NaN,NaN
1967739,2023-10-09,20:00:00,BROOKLYN,NaN,nan,1327 NEW YORK AVENUE,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669399,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
1967676,2023-10-09,19:58:00,BROOKLYN,BELT PARKWAY,nan,NaN,1.0,0.0,0,0,0,0,1,0,Unspecified,Unspecified,Unspecified,NaN,NaN,4669118,Sedan,Sedan,Sedan,NaN,NaN
1967148,2023-10-09,19:19:00,BROOKLYN,5 AVENUE,18 STREET,NaN,1.0,0.0,0,0,0,0,1,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669419,Sedan,NaN,NaN,NaN,NaN
1966297,2023-10-09,19:17:00,BROOKLYN,CROPSEY AVENUE,SHORE PARKWAY,NaN,1.0,0.0,0,0,0,0,1,0,Unsafe Speed,Unspecified,NaN,NaN,NaN,4669414,Sedan,Sedan,NaN,NaN,NaN
1967146,2023-10-09,19:17:00,BROOKLYN,NaN,nan,2555 LINDEN BOULEVARD,0.0,0.0,0,0,0,0,0,0,Passing Too Closely,Unspecified,NaN,NaN,NaN,4669128,Bus,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1966312,2023-10-09,19:15:00,QUEENS,CROSS ISLAND PARKWAY,UNION TURNPIKE,NaN,1.0,0.0,0,0,0,0,1,0,Unspecified,Unspecified,NaN,NaN,NaN,4669310,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1967771,2023-10-09,19:15:00,QUEENS,SAINT NICHOLAS,LINDEN STREET,NaN,1.0,0.0,0,0,0,0,1,0,Fatigued/Drowsy,Unspecified,Unspecified,Unspecified,NaN,4669255,Sedan,Station Wagon/Sport Utility Vehicle,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN
1967154,2023-10-09,19:12:00,QUEENS,158 AVENUE,84 STREET,NaN,1.0,0.0,0,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,4669149,Sedan,E-Bike,NaN,NaN,NaN
1967703,2023-10-09,19:08:00,MANHATTAN,2 AVENUE,nan,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669458,Station Wagon/Sport Utility Vehicle,Moped,NaN,NaN,NaN
1967679,2023-10-09,19:04:00,QUEENS,65 STREET,6 AVENUE,NaN,1.0,0.0,0,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669312,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN
1966256,2023-10-09,18:52:00,BROOKLYN,NaN,nan,2616 EAST 12 STREET,0.0,0.0,0,0,0,0,0,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669151,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1966290,2023-10-09,18:45:00,QUEENS,69 STREET,WOODSIDE AVENUE,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669234,Sedan,E-Scooter,NaN,NaN,NaN

In [16]:
df['BOROUGH'].unique()

array(['BROOKLYN', 'MANHATTAN', 'QUEENS', 'BRONX', 'STATEN ISLAND',
       'OTHER'], dtype=object)

In [15]:
# Drop rows where 'BOROUGH' is 'MANHATTAN' in the original DataFrame
df.drop(df[df['BOROUGH'] == 'nan'].index, inplace=True)

In [18]:
df['BOROUGH'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2004964 entries, 1967127 to 1924040
Series name: BOROUGH
Non-Null Count    Dtype
--------------    -----
2004964 non-null  object
dtypes: object(1)
memory usage: 30.6+ MB

In [19]:
df.head(40)

,CRASH DATE,CRASH TIME,BOROUGH,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
1967127,2023-10-09,23:50:00,BROOKLYN,BELT PARKWAY,nan,NaN,0.0,0.0,0,0,0,0,0,0,Alcohol Involvement,Unspecified,NaN,NaN,NaN,4669317,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1967707,2023-10-09,23:10:00,MANHATTAN,NaN,nan,59 WEST 44 STREET,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669164,Station Wagon/Sport Utility Vehicle,Box Truck,NaN,NaN,NaN
1966246,2023-10-09,23:02:00,BROOKLYN,OCEAN PARKWAY,CHURCH AVENUE,NaN,1.0,0.0,0,0,0,0,1,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669243,Sedan,Sedan,NaN,NaN,NaN
1967746,2023-10-09,23:00:00,MANHATTAN,1 AVENUE,EAST 46 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669154,Sedan,Van,NaN,NaN,NaN
1967789,2023-10-09,22:59:00,QUEENS,114 STREET,nan,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4669294,Sedan,Sedan,NaN,NaN,NaN
1967671,2023-10-09,22:55:00,QUEENS,21 STREET,43 AVENUE,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4669228,Motorscooter,NaN,NaN,NaN,NaN
1967784,2023-10-09,22:45:00,QUEENS,NaN,nan,131-22 LAURELTON PARKWAY,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,Unspecified,Unspecified,NaN,4669452,Pick-up Truck,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,NaN
1966309,2023-10-09,21:35:00,BROOKLYN,CHURCH AVENUE,EAST 8 STREET,NaN,1.0,0.0,0,0,1,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669236,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
1966240,2023-10-09,21:25:00,QUEENS,67 DRIVE,110 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Backing Unsafely,Unspecified,NaN,NaN,NaN,4669186,Pick-up Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1967745,2023-10-09,21:16:00,BROOKLYN,BELT PARKWAY,nan,NaN,0.0,1.0,0,1,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4669429,Sedan,NaN,NaN,NaN,NaN
1967780,2023-10-09,21:11:00,BROOKLYN,KINGSLAND AVENUE,EAST GUN HILL ROAD,NaN,3.0,0.0,0,0,0,0,3,0,Other Vehicular,Other Vehicular,NaN,NaN,NaN,4669250,Taxi,Sedan,NaN,NaN,NaN
1966302,2023-10-09,20:47:00,BRONX,EAST BURNSIDE AVENUE,ANTHONY AVENUE,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669203,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
1967773,2023-10-09,20:45:00,BROOKLYN,BROOKLYN QUEENS EXPRESSWAY,nan,NaN,4.0,0.0,0,0,0,0,4,0,Driver Inattention/Distraction,Following Too Closely,Following Too Closely,Following Too Closely,Unspecified,4669132,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,Sedan
1967738,2023-10-09,20:42:00,QUEENS,LIBERTY AVENUE,127 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4669150,Sedan,Dump,NaN,NaN,NaN
1967725,2023-10-09,20:36:00,BROOKLYN,NaN,nan,305 8 AVENUE,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669123,Taxi,Sedan,NaN,NaN,NaN
1967390,2023-10-09,20:30:00,BROOKLYN,BAY RIDGE AVENUE,nan,NaN,1.0,0.0,0,0,1,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669137,Sedan,E-Bike,NaN,NaN,NaN
1966307,2023-10-09,20:20:00,BROOKLYN,AVENUE L,EAST 92 STREET,NaN,3.0,0.0,0,0,0,0,3,0,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,4669156,Sedan,Sedan,NaN,NaN,NaN
1966242,2023-10-09,20:18:00,QUEENS,BELT PARKWAY,nan,NaN,2.0,0.0,0,0,0,0,2,0,Lost Consciousness,Unspecified,NaN,NaN,NaN,4669307,Sedan,Sedan,NaN,NaN,NaN
1967739,2023-10-09,20:00:00,BROOKLYN,NaN,nan,1327 NEW YORK AVENUE,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669399,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
1967676,2023-10-09,19:58:00,BROOKLYN,BELT PARKWAY,nan,NaN,1.0,0.0,0,0,0,0,1,0,Unspecified,Unspecified,Unspecified,NaN,NaN,4669118,Sedan,Sedan,Sedan,NaN,NaN
1967148,2023-10-09,19:19:00,BROOKLYN,5 AVENUE,18 STREET,NaN,1.0,0.0,0,0,0,0,1,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669419,Sedan,NaN,NaN,NaN,NaN
1966297,2023-10-09,19:17:00,BROOKLYN,CROPSEY AVENUE,SHORE PARKWAY,NaN,1.0,0.0,0,0,0,0,1,0,Unsafe Speed,Unspecified,NaN,NaN,NaN,4669414,Sedan,Sedan,NaN,NaN,NaN
1967146,2023-10-09,19:17:00,BROOKLYN,NaN,nan,2555 LINDEN BOULEVARD,0.0,0.0,0,0,0,0,0,0,Passing Too Closely,Unspecified,NaN,NaN,NaN,4669128,Bus,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1966312,2023-10-09,19:15:00,QUEENS,CROSS ISLAND PARKWAY,UNION TURNPIKE,NaN,1.0,0.0,0,0,0,0,1,0,Unspecified,Unspecified,NaN,NaN,NaN,4669310,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1967771,2023-10-09,19:15:00,QUEENS,SAINT NICHOLAS,LINDEN STREET,NaN,1.0,0.0,0,0,0,0,1,0,Fatigued/Drowsy,Unspecified,Unspecified,Unspecified,NaN,4669255,Sedan,Station Wagon/Sport Utility Vehicle,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN
1967154,2023-10-09,19:12:00,QUEENS,158 AVENUE,84 STREET,NaN,1.0,0.0,0,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,4669149,Sedan,E-Bike,NaN,NaN,NaN
1967703,2023-10-09,19:08:00,MANHATTAN,2 AVENUE,nan,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669458,Station Wagon/Sport Utility Vehicle,Moped,NaN,NaN,NaN
1967679,2023-10-09,19:04:00,QUEENS,65 STREET,6 AVENUE,NaN,1.0,0.0,0,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669312,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN
1966256,2023-10-09,18:52:00,BROOKLYN,NaN,nan,2616 EAST 12 STREET,0.0,0.0,0,0,0,0,0,0,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,4669151,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1966290,2023-10-09,18:45:00,QUEENS,69 STREET,WOODSIDE AVENUE,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4669234,Sedan,E-Scooter,NaN,NaN,NaN
1967719,2023-10-09,18:24:00,QUEENS,111 STREET,101 AVENUE,NaN,1.0,0.0,0,0,0,0,1,0,Pavement Defective,Following Too Closely,NaN,NaN,NaN,4669490,Sedan,Sedan,NaN,NaN,NaN
1967673,2023-10-09,18:23:00,BROOKLYN,NaN,nan,1015 WASHINGTON AVENUE,1.0,0.0,0,0,0,0,1,0,Driver Inattention/Distraction,Unsafe Speed,NaN,NaN,NaN,4669206,Sedan,Moped,NaN,NaN,NaN
1967769,2023-10-09,18:21:00,QUEENS,85 AVENUE,WOODHAVEN BOULEVARD,NaN,0.0,0.0,0,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,Unspecified,NaN,NaN,4669808,Sedan,Sedan,Sedan,NaN,NaN
1966327,2023-10-09,18:10:00,BRONX,SUMMIT AVENUE,WEST 161 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4669175,Station Wagon/Sport Utility Vehicle,Pick-up Truck,NaN,NaN,NaN
1967744,2023-10-09,18:10:00,BROOKLYN,ALBANY AVENUE,EMPIRE BOULEVARD,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4669205,Sedan,NaN,NaN,NaN,NaN
1967785,2023-10-09,18:07:00,QUEENS,21 STREET,49 AVENUE,NaN,1.0,0.0,1,0,0,0,0,0,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,4669233,Sedan,NaN,NaN,NaN,NaN
1966323,2023-10-09,17:55:00,QUEENS,GRAND AVENUE,66 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4669252,Convertible,Sedan,NaN,NaN,NaN
1967122,2023-10-09,17:40:00,BROOKLYN,MC DONALD AVENUE,GREENWOOD AVENUE,NaN,2.0,0.0,0,0,0,0,2,0,Driver Inattention/Distraction,Following Too Closely,NaN,NaN,NaN,4669121,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1967683,2023-10-09,17:35:00,MANHATTAN,NaN,nan,509 WEST 55 STREET,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669181,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1967698,2023-10-09,17:35:00,BROOKLYN,PROSPECT EXPRESSWAY,nan,NaN,1.0,0.0,0,0,1,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4669112,Sedan,Bike,NaN,NaN,NaN

In [9]:
filtered_df3 = df[df['BOROUGH'].isna() & (df['ON STREET NAME'].isna() | df['CROSS STREET NAME'].isna() | df['OFF STREET NAME'].isna())]
filtered_df3

Empty DataFrame
Columns: [CRASH DATE, CRASH TIME, BOROUGH, ON STREET NAME, CROSS STREET NAME, OFF STREET NAME, NUMBER OF PERSONS INJURED, NUMBER OF PERSONS KILLED, NUMBER OF PEDESTRIANS INJURED, NUMBER OF PEDESTRIANS KILLED, NUMBER OF CYCLIST INJURED, NUMBER OF CYCLIST KILLED, NUMBER OF MOTORIST INJURED, NUMBER OF MOTORIST KILLED, CONTRIBUTING FACTOR VEHICLE 1, CONTRIBUTING FACTOR VEHICLE 2, CONTRIBUTING FACTOR VEHICLE 3, CONTRIBUTING FACTOR VEHICLE 4, CONTRIBUTING FACTOR VEHICLE 5, COLLISION_ID, VEHICLE TYPE CODE 1, VEHICLE TYPE CODE 2, VEHICLE TYPE CODE 3, VEHICLE TYPE CODE 4, VEHICLE TYPE CODE 5]
Index: []

[0 rows x 25 columns]

In [ ]:
# Get all unique street names from the 'ON STREET NAME' column
unique_street_names = filtered_df3['OFF STREET NAME'].unique()

# Convert the unique street names to a Python list
unique_street_names_list = unique_street_names.tolist()

# Print the list of unique street names
for street_name in unique_street_names_list:
    print(street_name)

 "BOROUGH" is null, "ON STREET NAME" is 'WILLIAMSBURG BRIDGE,' and "OFF STREET NAME" is 'DRIGGS AVENUE

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'WILLIAMSBURG BRIDGE') & (df['OFF STREET NAME'] == 'DRIGGS AVENUE')

# Replace NaN values with 'MANHATTAN' where the mask is True
df.loc[mask, 'BOROUGH'] = 'MANHATTAN'

ON STREET = BELT PARKWAY

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'BELT PARKWAY')

# Replace NaN values with 'BROOKLYN' where the mask is True
df.loc[mask, 'BOROUGH'] = 'BROOKLYN'

on street = long island express way

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'LONG ISLAND EXPRESSWAY')

# Replace NaN values with 'QUEENS' where the mask is True
df.loc[mask, 'BOROUGH'] = 'QUEENS'

on street name is rockaway parkway and cross street name is shore parkway

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'ROCKAWAY PARKWAY') & (df['CROSS STREET NAME'] == 'SHORE PARKWAY')

# Replace NaN values with 'BROOKLYN' where the mask is True
df.loc[mask, 'BOROUGH'] = 'BROOKLYN'

on street name is 68 street and cross street name is 3 avenue

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == '68 STREET') & (df['CROSS STREET NAME'] == '3 AVENUE')

# Replace NaN values with 'BROOKLYN' where the mask is True
df.loc[mask, 'BOROUGH'] = 'BROOKLYN'

on street name is hylan boulevard and cross str name is narrows road south

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'HYLAN BOULEVARD') & (df['CROSS STREET NAME'] == 'NARROWS ROAD SOUTH')

# Replace NaN values with 'STATEN ISLAND' where the mask is True
df.loc[mask, 'BOROUGH'] = 'STATEN ISLAND'

on str is caney lane street and cross str is hookcreek boulevard str

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'CANEY LANE') & (df['CROSS STREET NAME'] == 'HOOK CREEK BOULEVARD')

# Replace NaN values with 'QUEENS' where the mask is True
df.loc[mask, 'BOROUGH'] = 'QUEENS'

on str is caney lane and cross str is hookcreek boulevard str

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['ON STREET NAME'] == 'CANEY LANE') & (df['CROSS STREET NAME'] == 'HOOKCREEK BOULEVARD')

# Replace NaN values with 'QUEENS' where the mask is True
df.loc[mask, 'BOROUGH'] = 'QUEENS'

off street is PARKING LOT OF 154-02 HORACE HARDING

In [ ]:
# Create a boolean mask for the specified conditions
mask = (df['BOROUGH'].isna()) & (df['OFF STREET NAME'] == 'PARKING LOT OF 154-02 HORACE HARDING')

# Replace NaN values with 'QUEENS' where the mask is True
df.loc[mask, 'BOROUGH'] = 'QUEENS'

In [ ]:
filtered_df3 = df[df['BOROUGH'].isna() & (df['ON STREET NAME'].isna() | df['CROSS STREET NAME'].isna() | df['OFF STREET NAME'].isna())]
filtered_df3